openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
  - url: http://127.0.0.1:8000/
    description: "Local Server"
paths:
  "/winners/{year}":
    get:
      summary: Get Year Winners
      operationId: get_year_winners_winners__year__get
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: integer
            title: Year
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/YearWinnersResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  "/winners/{year}/{race}":
    get:
      summary: Get Race Winner
      operationId: get_race_winner_winners__year___race__get
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: integer
            title: Year
        - name: race
          in: path
          required: true
          schema:
            type: string
            title: Race
            description: "The name of the race. Use underscores (_) to separate words in race names (e.g., 'cape_town')."
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RaceWinnerResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      type: object
      title: HTTPValidationError
      properties:
        detail:
          type: array
          title: Detail
          items:
            $ref: "#/components/schemas/ValidationError"
    ValidationError:
      type: object
      title: ValidationError
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          title: Location
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
    RaceWinner:
      type: object
      title: RaceWinner
      required:
        - race
        - winner
      properties:
        race:
          type: string
          title: Race
        winner:
          type: string
          title: Winner
    RaceWinnerResponse:
      type: object
      title: RaceWinnerResponse
      required:
        - year
        - race
        - winner
      properties:
        year:
          type: integer
          title: Year
        race:
          type: string
          title: Race
        winner:
          type: string
          title: Winner
    YearWinnersResponse:
      type: object
      title: YearWinnersResponse
      required:
        - year
        - winners
      properties:
        year:
          type: integer
          title: Year
        winners:
          type: array
          title: Winners
          items:
            $ref: "#/components/schemas/RaceWinner"
